blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/rpothin/PowerPlatform-ALM-With-GitHub-Template/discussions
    about: Please follow this link to participate to the discussions.